# Generated by Django 5.1.4 on 2025-05-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
