# Generated by Django 5.1.4 on 2025-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
